//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoomAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoom_Messages
    {
        public int Id { get; set; }
        public int IdRoom { get; set; }
        public int IdUser { get; set; }
        public int IdState { get; set; }
        public string MessageText { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        public virtual ChatRoom_cState ChatRoom_cState { get; set; }
        public virtual ChatRoom_Rooms ChatRoom_Rooms { get; set; }
        public virtual ChatRoom_Users ChatRoom_Users { get; set; }
    }
}
