//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoomAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatRoomDBEntities : DbContext
    {
        public ChatRoomDBEntities()
            : base("name=ChatRoomDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatRoom_cState> ChatRoom_cState { get; set; }
        public virtual DbSet<ChatRoom_Messages> ChatRoom_Messages { get; set; }
        public virtual DbSet<ChatRoom_Rooms> ChatRoom_Rooms { get; set; }
        public virtual DbSet<ChatRoom_Users> ChatRoom_Users { get; set; }
    }
}
